import stylistic from '@stylistic/eslint-plugin'
import globals from 'globals'

export default [
  {
    files: ['src/**/*.mjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.node,
        ...globals.es2021,
        BigInt: true
      }
    },
    plugins: {
      '@stylistic': stylistic
    },
    rules: {
      // --- Core ESLint rules (non-stylistic) ---
      'for-direction': 'error',
      'getter-return': 'warn',
      'no-console': 'off',
      'no-empty': ['warn', {allowEmptyCatch: true}],
      'require-atomic-updates': 'off',
      'dot-notation': 'warn',
      'eqeqeq': ['error', 'smart'],
      'guard-for-in': 'error',
      'no-caller': 'error',
      'no-empty-pattern': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-label': 'error',
      'no-implicit-coercion': 'error',
      'no-implied-eval': 'error',
      'no-labels': ['error', {allowLoop: true}],
      'no-lone-blocks': 'warn',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-octal-escape': 'error',
      'no-return-assign': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-unmodified-loop-condition': 'warn',
      'no-useless-call': 'error',
      'no-useless-concat': 'warn',
      'no-useless-return': 'warn',
      'no-void': 'error',
      'no-with': 'error',
      'no-label-var': 'error',
      'no-shadow-restricted-names': 'error',
      'no-undef-init': 'error',
      'no-unused-vars': 'warn',
      'no-use-before-define': ['error', {functions: false, classes: false}],
      'no-array-constructor': 'error',
      'no-var': 'error',
      'no-useless-computed-key': 'warn',
      'no-useless-constructor': 'warn',
      'no-useless-rename': 'warn',
      'no-duplicate-imports': 'warn',
      'object-shorthand': 'warn',
      'prefer-arrow-callback': 'warn',
      'prefer-numeric-literals': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'warn',
      'prefer-template': 'warn',
      'arrow-body-style': ['warn', 'as-needed'],

      // --- Stylistic rules (moved to @stylistic in ESLint v10) ---
      '@stylistic/array-bracket-newline': ['warn', 'consistent'],
      '@stylistic/array-bracket-spacing': 'warn',
      '@stylistic/arrow-parens': ['warn', 'as-needed'],
      '@stylistic/arrow-spacing': 'warn',
      '@stylistic/brace-style': ['warn', '1tbs', {allowSingleLine: true}],
      '@stylistic/comma-spacing': 'warn',
      '@stylistic/comma-style': 'warn',
      '@stylistic/computed-property-spacing': 'warn',
      '@stylistic/eol-last': 'error',
      '@stylistic/function-call-spacing': 'warn',
      '@stylistic/generator-star-spacing': ['warn', {before: false, after: true}],
      '@stylistic/implicit-arrow-linebreak': 'warn',
      '@stylistic/indent': ['warn', 2],
      '@stylistic/key-spacing': 'warn',
      '@stylistic/keyword-spacing': 'warn',
      '@stylistic/linebreak-style': 'error',
      '@stylistic/newline-per-chained-call': 'warn',
      '@stylistic/no-extra-parens': 'warn',
      '@stylistic/no-floating-decimal': 'warn',
      '@stylistic/no-multi-spaces': 'warn',
      '@stylistic/no-multiple-empty-lines': ['error', {max: 2, maxEOF: 1, maxBOF: 0}],
      '@stylistic/no-tabs': 'error',
      '@stylistic/no-trailing-spaces': 'warn',
      '@stylistic/no-whitespace-before-property': 'warn',
      '@stylistic/nonblock-statement-body-position': 'error',
      '@stylistic/object-curly-newline': 'warn',
      '@stylistic/object-curly-spacing': 'warn',
      '@stylistic/operator-linebreak': ['warn', 'before'],
      '@stylistic/padded-blocks': ['warn', 'never'],
      '@stylistic/quote-props': ['warn', 'as-needed'],
      '@stylistic/quotes': ['warn', 'single', {avoidEscape: true, allowTemplateLiterals: 'always'}],
      '@stylistic/rest-spread-spacing': 'warn',
      '@stylistic/semi': ['warn', 'never'],
      '@stylistic/semi-spacing': 'warn',
      '@stylistic/semi-style': 'warn',
      '@stylistic/space-before-blocks': 'warn',
      '@stylistic/space-before-function-paren': ['warn', {
        anonymous: 'never',
        named: 'never',
        asyncArrow: 'always'
      }],
      '@stylistic/space-in-parens': 'warn',
      '@stylistic/space-infix-ops': 'warn',
      '@stylistic/space-unary-ops': ['warn', {words: true, nonwords: false}],
      '@stylistic/switch-colon-spacing': 'warn',
      '@stylistic/template-curly-spacing': 'warn',
      '@stylistic/template-tag-spacing': 'warn',
      '@stylistic/wrap-iife': 'error',
      '@stylistic/yield-star-spacing': 'warn'
    }
  },
  {
    ignores: ['node_modules/**', 'dist/**', 'config/**', 'src/migrations/**', 'src/seeders/**']
  }
]
